databases:
  - name: mysite
    databaseName: egypt
    user: kemet
    plan: free


services:
  - type: web
    name: mysite
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        value: "postgresql://kemet:4321@localhost/egypt"
      - key: RAILS_MASTER_KEY
        sync: false
